<a href="https://colab.research.google.com/github/nirmeshbansal/tfbasic/blob/master/tflayer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import tensorflow as tf

In [0]:
import numpy as np


In [0]:
a = [-40, -10,  0,  8, 15, 22,  38]
b= [-40,  14, 32, 46, 59, 72, 100]


In [0]:
a=np.array(a)

In [0]:
b=np.array(b)

In [23]:
a

array([-40, -10,   0,   8,  15,  22,  38])

In [0]:
model=tf.keras.Sequential([tf.keras.layers.Dense(units=4, input_shape=[1]), tf.keras.layers.Dense(units=2), tf.keras.layers.Dense(units=1)])

In [0]:
model.compile(loss="mean_squared_error",optimizer=tf.keras.optimizers.Adam(0.1))

In [26]:
model.fit(a,b,epochs=500,verbose=False)
print("Trained")

Trained


In [27]:
model.predict([100])

array([[211.74744]], dtype=float32)

In [29]:
model.predict([0,3])

array([[31.952528],
       [37.34637 ]], dtype=float32)